carservice/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    # path('ser/', views.services, name='ser'),

]

carservice_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView


urlpatterns = [
    path('carservice/', include('carservice.urls')),
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='carservice/', permanent=True)), # padaro homepage, redirektina
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

carservice/models.py
# Create your models here.
from django.db import models


class CarModel(models.Model):
    car_name = models.CharField(verbose_name='Car Manufacturer', max_length=50, help_text='Įveskite automobilio gamintojo pavadinimą',
                                null=False)
    car_model = models.CharField(verbose_name='Model', max_length=50, help_text='Įveskite automobilio modelio pavadinimą',
                                 null=False)

    def __str__(self):
        return f'{self.car_name}, {self.car_model}'

    class Meta:
        verbose_name = 'Car model'
        verbose_name_plural = 'Car models'


class Automobile(models.Model):
    car_plate = models.CharField(verbose_name="Plate number",  max_length=10, unique=True, null=False)
    car_model = models.ForeignKey('CarModel', on_delete=models.DO_NOTHING)  # kaip čia su True daryti?
    vin_code = models.CharField(verbose_name='VIN number', max_length=17, help_text='Automobile VIN code', unique=True, null=False)
    customer = models.CharField(verbose_name='Customer', max_length=30, help_text='Customer Name Surname (or Company Name)')

    def __str__(self):
        return f'{self.car_plate}, {self.car_model}, {self.vin_code}, {self.customer}'

    class Meta:
        verbose_name = 'Automobile'
        verbose_name_plural = 'Automobiles'


class Order(models.Model):
    order_date = models.DateField('Order date', null=False)
    car = models.ForeignKey('Automobile', on_delete=models.DO_NOTHING)

    LOAN_STATUS = (
        ('n', 'New'),
        ('i', 'In progress'),
        ('d', 'Works Done'),
        ('c', 'Closed'),
    )

    order_status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='n',
        help_text='Order Status',
    )

    class Meta:
        ordering = ['-order_status', "order_date"]
        verbose_name = 'Order'
        verbose_name_plural = 'Orders'

    def __str__(self):
        return f'{self.order_date}, {self.order_status}, {self.car}'



class ServiceOrder(models.Model):
    order = models.ForeignKey('Order', on_delete=models.DO_NOTHING)
    service = models.ForeignKey('Service', on_delete=models.DO_NOTHING)
    qty = models.DecimalField('Qty.', max_digits=12, decimal_places=1, null=False)

    LOAN_STATUS = (
        ('1', 'Not Started'),
        ('2', 'Planned'),
        ('3', 'In progress'),
        ('4', 'Blocked'),
        ('5', 'Done'),
    )

    service_status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='1',
        help_text='Service Status',
    )


    def __str__(self):
        return f'{self.order}, {self.service}, {self.qty}, {self.service_status}'

    class Meta:
        ordering = ['order__order_date', 'service_status']
        verbose_name = 'Service order'
        verbose_name_plural = 'Service orders'


class Service(models.Model):
    service_name = models.CharField('Service name', max_length=200, null=False)
    service_price = models.DecimalField('Service price', max_digits=12, decimal_places=2, null=False)

    def __str__(self):
        return f'{self.service_name}, {self.service_price}'

    class Meta:
        ordering = ['service_name']
        verbose_name = 'Service'
        verbose_name_plural = 'Services'

carservice/views.py
# Create your views here.
from django.shortcuts import render
from django.http import HttpResponse
from .models import CarModel, Automobile, Order, ServiceOrder, Service


def index(request):
    # Suskaičiuokime keletą pagrindinių objektų
    num_car_models = CarModel.objects.all().count()
    num_automobiles = Automobile.objects.all().count()
    num_orders = Order.objects.all().count()
    num_service_orders = ServiceOrder.objects.all().count()
    num_services = Service.objects.all().count()

    # Orders by status
    num_order_1 = Order.objects.filter(order_status__exact='n').count()
    num_order_2 = Order.objects.filter(order_status__exact='i').count()
    num_order_3 = Order.objects.filter(order_status__exact='d').count()
    num_order_4 = Order.objects.filter(order_status__exact='c').count()

    # Services by status
    num_service_status_1 = ServiceOrder.objects.filter(service_status__exact='1').count()
    num_service_status_2 = ServiceOrder.objects.filter(service_status__exact='2').count()
    num_service_status_3 = ServiceOrder.objects.filter(service_status__exact='3').count()
    num_service_status_4 = ServiceOrder.objects.filter(service_status__exact='4').count()
    num_service_status_5 = ServiceOrder.objects.filter(service_status__exact='5').count()


    # perduodame informaciją į šabloną žodyno pavidale:
    context = {
        'num_car_models': num_car_models,
        'num_automobiles': num_automobiles,
        'num_orders': num_orders,
        'num_services': num_services,
        'num_service_orders': num_service_orders,
        'num_order_1': num_order_1,
        'num_order_2': num_order_2,
        'num_order_3': num_order_3,
        'num_order_4': num_order_4,
        'num_service_status_1': num_service_status_1,
        'num_service_status_2': num_service_status_2,
        'num_service_status_3': num_service_status_3,
        'num_service_status_4': num_service_status_4,
        'num_service_status_5': num_service_status_5,

    }

    # renderiname base.html, su duomenimis kintamąjame context
    return render(request, 'base.html', context=context)



# def services(request):
#     return render(request, 'services.html')

carservice/templates/album.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>

carservice/templates/automobile_list.html
{% extends "base.html" %}

{% block content %}
  <h1>Our happy customers drive:</h1>
  {% if automobile_list %}
  <ul>
    {% for automobile in automobile_list %}
      <li>
        <a href="{{ automobile.id }}">{{ automobile.car_plate }}</a> ({{automobile.vin_code}})
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>Customers' list is private</p>
  {% endif %}
{% endblock %}

carservice/templates/base_login.html
{% extends "base.html" %}
{% load static %}
{% block layout %}

<div class="d-flex justify-content-center align-items-center min-vh-100" style="position: relative;">
    <div class="card p-5 shadow-lg rounded-lg" style="width: 100%; max-width: 500px; position: absolute;">

{% block content %}
        {% endblock %}
    </div>
</div>
{% endblock %}

carservice/templates/customer_detail.html
{% extends "base.html" %}

{% block content %}
<h1>Customer</h1>
<p>Automobilis:<strong> {{ order.car.car_model }}</strong></p>
<p>Valstybinis numeris:<strong> {{ order.car.car_plate }}</strong></p>
<p>VIN kodas:<strong> {{ order.car.vin_code }}</strong></p>
<p>Klientas:<strong> {{ order.car.customer }}</strong></p>
<br>
<h4>Service Orders:</h4>
<ul>
    {% for service_order in order.serviceorder_set.all %}
    <li>
        <p>
            Service: <strong>{{ service_order.service.service_name }}</strong>
            Quantity: <strong>{{ service_order.qty }}</strong>
            Status: <strong class="{% if service_order.service_status == '1' %}text-danger{% elif service_order.service_status == '2' or service_order.service_status == '3' %}text-warning{% else %}text-success{% endif %}">
                {{ service_order.get_service_status_display }}
            </strong>
        </p>
    </li>
    {% empty %}
    <p>No services associated with this order.</p>
    {% endfor %}
</ul>
{% endblock %}

carservice/templates/customer_list.html
{% extends "base.html" %}

{% block content %}
  <h1>Our happy customers drive:</h1>


  {% if automobile_list %}
  <ul>
    {% for automobile in automobile_list %}
      <li>
     <a href="{{ automobile.id }}">{{ automobile.car_model }}</a> ({{automobile.vin_code}})-->
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>Customers' list is private</p>
  {% endif %}
{% endblock %}

carservice/templates/index.html
{% extends "base.html" %}

{% block content %}
  <h1>PyCar Service</h1>
            <p>Welcome to our world!</p>
            <p>Currently we have:</p>
            <ul>
                <li><strong>Total car models:</strong> {{ num_car_models }}</li>
                <li><strong>Customers:</strong> {{ num_automobiles }}</li>
                <li><strong>Total orders:</strong> {{ num_orders }}</li>
                <li><strong>Number of Services:</strong> {{ num_services }}</li>
                <li><strong>Number of Service Orders:</strong> {{ num_service_orders }}</li>
                <br>
                <li><strong>Orders by Status 'New':</strong> {{ num_order_1 }}</li>
                <li><strong>Orders by Status 'In Progress':</strong> {{ num_order_2 }}</li>
                <li><strong>Orders by Status 'Works Done':</strong> {{ num_order_3 }}</li>
                <li><strong>Orders by Status 'Closed':</strong> {{ num_order_4 }}</li>
                <br>
                <li><strong>Services by Status 'Not Started':</strong> {{ num_service_status_1 }}</li>
                <li><strong>Services by Status 'Planned':</strong> {{ num_service_status_2 }}</li>
                <li><strong>Services by Status 'In progress':</strong> {{ num_service_status_3 }}</li>
                <li><strong>Services by Status 'Blocked':</strong> {{ num_service_status_4 }}</li>
                <li><strong>Services by Status 'Done':</strong> {{ num_service_status_5 }}</li>

  </ul>
{% endblock %}

carservice/templates/mfa/authenticate.html
{% extends "mfa/base_entrance.html" %}
{% load i18n %}
{% load allauth %}
{% load allauth static %}
{% block head_title %}
    {% trans "Sign In" %}
{% endblock head_title %}
{% block content %}
    {% element h1 %}
        {% trans "Two-Factor Authentication" %}
    {% endelement %}
    {% element p %}
        {% blocktranslate %}Your account is protected by two-factor authentication. Please enter an authenticator code:{% endblocktranslate %}
    {% endelement %}
    {% url 'mfa_authenticate' as action_url %}
    {% element form form=form method="post" action=action_url %}
        {% slot body %}
            {% csrf_token %}
            {% element fields form=form unlabeled=True %}
            {% endelement %}
        {% endslot %}
        {% slot actions %}
            {% element button type="submit" tags="primary,mfa,login" %}
                {% trans "Sign In" %}
            {% endelement %}
            {% if "webauthn" not in MFA_SUPPORTED_TYPES %}
                {% element button type="submit" form="logout-from-stage" tags="link,mfa,cancel" %}
                    {% trans "Cancel" %}
                {% endelement %}
            {% endif %}
        {% endslot %}
    {% endelement %}
    {% if "webauthn" in MFA_SUPPORTED_TYPES %}
        {% element hr %}
        {% endelement %}
        {% element h2 %}
            {% translate "Alternative options" %}
        {% endelement %}
        {% element button_group vertical=True %}
            {% element button form="webauthn_form" id="mfa_webauthn_authenticate" type="button" tags="outline,primary" %}
                {% trans "Use a security key" %}
            {% endelement %}
            {% element button type="submit" form="logout-from-stage" tags="outline,primary,mfa,cancel" %}
                {% trans "Cancel" %}
            {% endelement %}
        {% endelement %}
        {% if "webauthn" in MFA_SUPPORTED_TYPES %}
            {% element form id="webauthn_form" form=webauthn_form method="post" action=action_url no_visible_fields=True %}
                {% slot body %}
                    {% csrf_token %}
                    {% element fields form=webauthn_form %}
                    {% endelement %}
                {% endslot %}
            {% endelement %}
            {{ js_data|json_script:"js_data" }}
            {% include "mfa/webauthn/snippets/scripts.html" %}
            <script>
        allauth.webauthn.forms.authenticateForm({
        ids: {
        authenticate: "mfa_webauthn_authenticate",
        credential: "{{ webauthn_form.credential.auto_id }}"
        },
        data: JSON.parse(document.getElementById('js_data').textContent)
        })
            </script>
        {% endif %}
    {% endif %}
    <form id="logout-from-stage"
          method="post"
          action="{% url 'account_logout' %}">
        <input type="hidden" name="next" value="{% url 'account_login' %}">
        {% csrf_token %}
    </form>
{% endblock content %}

carservice/templates/mfa/base_entrance.html
{% extends "allauth/layouts/entrance.html" %}

carservice/templates/mfa/base_manage.html
{% extends "allauth/layouts/manage.html" %}

carservice/templates/mfa/index.html
{% extends "mfa/base_manage.html" %}
{% load allauth %}
{% load i18n %}
{% block head_title %}
    {% trans "Two-Factor Authentication" %}
{% endblock head_title %}
{% block content %}
    {% element h1 tags="mfa,index" %}
        {% trans "Two-Factor Authentication" %}
    {% endelement %}
    {% if "totp" in MFA_SUPPORTED_TYPES %}
        {% element panel %}
            {% slot title %}
                {% translate "Authenticator App" %}
            {% endslot %}
            {% slot body %}
                {% if authenticators.totp %}
                    {% element p %}
                        {% translate "Authentication using an authenticator app is active." %}
                    {% endelement %}
                {% else %}
                    {% element p %}
                        {% translate "An authenticator app is not active." %}
                    {% endelement %}
                {% endif %}
            {% endslot %}
            {% slot actions %}
                {% url 'mfa_deactivate_totp' as deactivate_url %}
                {% url 'mfa_activate_totp' as activate_url %}
                {% if authenticators.totp %}
                    {% element button href=deactivate_url tags="danger,delete,panel" %}
                        {% translate "Deactivate" %}
                    {% endelement %}
                {% else %}
                    {% element button href=activate_url tags="panel" %}
                        {% translate "Activate" %}
                    {% endelement %}
                {% endif %}
            {% endslot %}
        {% endelement %}
    {% endif %}
    {% if "webauthn" in MFA_SUPPORTED_TYPES %}
        {% element panel %}
            {% slot title %}
                {% translate "Security Keys" %}
            {% endslot %}
            {% slot body %}
                {% if authenticators.webauthn|length %}
                    {% element p %}
                        {% blocktranslate count count=authenticators.webauthn|length %}You have added {{ count }} security key.{% plural %}You have added {{ count }} security keys.{% endblocktranslate %}
                    {% endelement %}
                {% else %}
                    {% element p %}
                        {% translate "No security keys have been added." %}
                    {% endelement %}
                {% endif %}
            {% endslot %}
            {% slot actions %}
                {% if authenticators.webauthn|length %}
                    {% url 'mfa_list_webauthn' as webauthn_list_url %}
                    {% element button href=webauthn_list_url %}
                        {% translate "Manage" %}
                    {% endelement %}
                {% else %}
                    {% url 'mfa_add_webauthn' as webauthn_add_url %}
                    {% element button href=webauthn_add_url %}
                        {% translate "Add" %}
                    {% endelement %}
                {% endif %}
            {% endslot %}
        {% endelement %}
    {% endif %}
    {% if "recovery_codes" in MFA_SUPPORTED_TYPES %}
        {% with total_count=authenticators.recovery_codes.generate_codes|length unused_count=authenticators.recovery_codes.get_unused_codes|length %}
            {% element panel %}
                {% slot title %}
                    {% translate "Recovery Codes" %}
                {% endslot %}
                {% slot body %}
                    {% if authenticators.recovery_codes %}
                        {% element p %}
                            {% blocktranslate count unused_count=unused_count %}There is {{ unused_count }} out of {{ total_count }} recovery codes available.{% plural %}There are {{ unused_count }} out of {{ total_count }} recovery codes available.{% endblocktranslate %}
                        {% endelement %}
                    {% else %}
                        {% element p %}
                            {% translate "No recovery codes set up." %}
                        {% endelement %}
                    {% endif %}
                {% endslot %}
                {% if is_mfa_enabled %}
                    {% if authenticators.recovery_codes %}
                        {% if unused_count > 0 %}
                            {% slot actions %}
                                {% url 'mfa_view_recovery_codes' as view_url %}
                                {% element button href=view_url tags="panel" %}
                                    {% translate "View" %}
                                {% endelement %}
                            {% endslot %}
                            {% slot actions %}
                                {% url 'mfa_download_recovery_codes' as download_url %}
                                {% element button href=download_url tags="secondary,panel" %}
                                    {% translate "Download" %}
                                {% endelement %}
                            {% endslot %}
                        {% endif %}
                    {% endif %}
                    {% slot actions %}
                        {% url 'mfa_generate_recovery_codes' as generate_url %}
                        {% element button href=generate_url tags="secondary,panel" %}
                            {% translate "Generate" %}
                        {% endelement %}
                    {% endslot %}
                {% endif %}
            {% endelement %}
        {% endwith %}
    {% endif %}
{% endblock content %}

carservice/templates/mfa/reauthenticate.html
{% extends "account/base_reauthenticate.html" %}
{% load i18n %}
{% load allauth %}
{% block reauthenticate_content %}
    {% element p %}
        {% blocktranslate %}Enter an authenticator code:{% endblocktranslate %}
    {% endelement %}
    {% url 'mfa_reauthenticate' as action_url %}
    {% element form form=form method="post" action=action_url %}
        {% slot body %}
            {% csrf_token %}
            {% element fields form=form unlabeled=True %}
            {% endelement %}
            {{ redirect_field }}
        {% endslot %}
        {% slot actions %}
            {% element button type="submit" tags="primary,mfa,login" %}
                {% trans "Confirm" %}
            {% endelement %}
        {% endslot %}
    {% endelement %}
{% endblock %}

carservice/templates/mfa/recovery_codes/base.html
{% extends "mfa/base_manage.html" %}
{% load i18n %}
{% block head_title %}
    {% trans "Recovery Codes" %}
{% endblock head_title %}

carservice/templates/mfa/recovery_codes/generate.html
{% extends "mfa/recovery_codes/base.html" %}
{% load i18n %}
{% load allauth %}
{% block content %}
    {% element h1 %}
        {% translate "Recovery Codes" %}
    {% endelement %}
    {% element p %}
        {% blocktranslate %}You are about to generate a new set of recovery codes for your account.{% endblocktranslate %}
        {% if unused_code_count %}
            {% blocktranslate %}This action will invalidate your existing codes.{% endblocktranslate %}
        {% endif %}
        {% blocktranslate %}Are you sure?{% endblocktranslate %}
    {% endelement %}
    {% url 'mfa_generate_recovery_codes' as action_url %}
    {% element form method="post" action=action_url no_visible_fields=True %}
        {% slot body %}
            {% csrf_token %}
            {{ form.as_p }}
        {% endslot %}
        {% slot actions %}
            {% setvar tags %}
                {% if unused_code_count %}
                    danger
                {% else %}
                {% endif %}
            {% endsetvar %}
            {% element button type="submit" tags=tags %}
                {% trans "Generate" %}
            {% endelement %}
        {% endslot %}
    {% endelement %}
{% endblock content %}

carservice/templates/mfa/recovery_codes/index.html
{% extends "mfa/recovery_codes/base.html" %}
{% load i18n %}
{% load allauth %}
{% block content %}
    {% element h1 %}
        {% translate "Recovery Codes" %}
    {% endelement %}
    {% element p %}
        {% blocktranslate count unused_count=unused_codes|length %}There is {{ unused_count }} out of {{ total_count }} recovery codes available.{% plural %}There are {{ unused_count }} out of {{ total_count }} recovery codes available.{% endblocktranslate %}
    {% endelement %}
    {% element field id="recovery_codes" type="textarea" disabled=True rows=unused_codes|length readonly=True %}
        {% slot label %}
            {% translate "Unused codes" %}
        {% endslot %}
        {% comment %} djlint:off {% endcomment %}
    {% slot value %}{% for code in unused_codes %}{% if forloop.counter0 %}
{% endif %}{{ code }}{% endfor %}{% endslot %}
{% comment %} djlint:on {% endcomment %}
{% endelement %}
{% if unused_codes %}
{% url 'mfa_download_recovery_codes' as download_url %}
{% element button href=download_url %}
{% translate "Download codes" %}
{% endelement %}
{% endif %}
{% url 'mfa_generate_recovery_codes' as generate_url %}
{% element button href=generate_url %}
{% translate "Generate new codes" %}
{% endelement %}
{% endblock content %}

carservice/templates/user_order_detail.html
{% extends "base.html" %}

{% block content %}
<br>
<h1>
    <span class="{% if order.order_status == '1' %}text-danger{% elif order.order_status == '2' %}text-warning{% elif order.order_status == '5' %}text-secondary{% else %}text-success{% endif %}">
        {{ order.get_order_status_display }}
    </span> | {{ order.order_date }}
</h1>
<br>
<p>Automobile: <strong>{{ order.car.car_model }}</strong></p>
<p>Reg. plate number: <strong>{{ order.car.car_plate }}</strong></p>
<p>VIN: <strong>{{ order.car.vin_code }}</strong></p>
<p>Customer: <strong>{{ order.car.customer }}</strong></p>
<br>


<p>Planned return date: <strong><span class="{% if order.is_overdue %}text-danger{% else %}text-warning{% endif %}">{{ order.due_back }}</span></strong></p>

<br>
<h4>Service Requests:</h4>
<table class="table table-borderless">
    <thead>
        <tr>
            <th>Service name</th>
            <th>Qty</th>
            <th>Status</th>
            <th>Price</th>
            <th>Total</th>
        </tr>
    </thead>
    <tbody>
        {% for service_request in order.serviceorder_set.all %}
        <tr>
            <td>{{ service_request.service.service_name }}</td>
            <td>{{ service_request.qty }}</td>
            <td class="{% if service_request.service_status == '1' %}text-danger{% elif service_request.service_status == '2' or service_request.service_status == '3' %}text-warning{% elif service_request.service_status == '6' %}text-secondary{% else %}text-success{% endif %}">
                {{ service_request.get_service_status_display }}
            </td>
            <td>{{ service_request.service.service_price }} Eur</td>
            <td>{{ service_request.total_service_price }} Eur</td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="5">No services associated with this order.</td>
        </tr>
        {% endfor %}
    </tbody>
    <tfoot>
        <tr>
            <td colspan="4" class="text-end"><strong>Total Order Sum:</strong></td>
            <td><strong>{{ order.total_order_sum }} Eur</strong></td>
        </tr>
    </tfoot>
</table>
<br>
<br>
<button type="button" class="btn btn-secondary btn-sm" onclick="window.history.back();">Back</button>
{% endblock %}

carservice/templates/user_order_form.html
{% extends "base.html" %}

{% block content %}
<br>
  <h1>All Your Orders:</h1>


  {% if order_list %}

<table class="table table-hover">
  <thead>
    <tr>
      <th>Status</th>
      <th>Order Date</th>
      <th>Car Model</th>
        <th>Total Sum</th>
    </tr>
  </thead>
  <tbody>
    {% for order in order_list %}
      <tr>
        <td>
          <a href="{% url 'order-detail' order.pk %}" class="{% if order.order_status == '1' %}text-danger{% elif order.order_status == '2' or order.order_status == '3' %}text-warning{% elif order.order_status == '5' %}text-secondary{% else %}text-success{% endif %}">
            {{ order.get_order_status_display }}
          </a>
        </td>
        <td>{{ order.order_date }}</td>
        <td>{{ order.car.car_model }}</td>
          <td>{{ order.total_order_sum }} Eur</td>
      </tr>
    {% endfor %}
  </tbody>
</table>













<!--#puslapiavimas-->
<div style="text-align: center; font-size: 14px; color: #333;">
    <span class="step-links" style="display: inline-block;">
        {% if page_obj.has_previous %}
            <a href="?page=1" style="color: #333;">&laquo; pirmas</a>
            <a href="?page={{ page_obj.previous_page_number }}" style="color: #333;">atgal</a>
        {% endif %}

        <span class="current">
            {{ page_obj.number }} iš {{ page_obj.paginator.num_pages }}
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}" style="color: #333;">pirmyn</a>
            <a href="?page={{ page_obj.paginator.num_pages }}" style="color: #333;">paskutinis &raquo;</a>
        {% endif %}
    </span>
</div>

<section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">Album example</h1>
        <p class="lead text-body-secondary">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don’t simply skip over it entirely.</p>
        <p>
          <a href="#" class="btn btn-primary my-2">Main call to action</a>
          <a href="#" class="btn btn-secondary my-2">Secondary action</a>
        </p>
      </div>
    </div>
  </section>

  {% else %}
<br>
    <p>You don't have service orders</p>
  {% endif %}
{% endblock %}

carservice/templates/user_order_list.html
{% extends "base.html" %}

{% block content %}
<br>
  <h1>All Orders:</h1>


  {% if order_list %}

<!--  <ul>-->
<!--    {% for order in order_list %}-->
<!--      <li>-->
<!--        <a href="{{ order.id }}" class="{% if order.order_status == '1' %}text-danger{% elif order.order_status == '2' or order.order_status == '3' %}text-warning{% elif order.order_status == '5' %}text-secondary{% else %}text-success{% endif %}">-->
<!--{{ order.get_order_status_display }}</a> | {{order.order_date}} | {{ order.car.car_model}}-->
<!--      </li>-->
<!--    {% endfor %}-->
<!--     </ul>-->


<table class="table table-hover">
  <thead>
    <tr>
      <th>Status</th>
      <th>Order Date</th>
      <th>Car Model</th>
        <th>Total Sum</th>
    </tr>
  </thead>
  <tbody>
    {% for order in order_list %}
      <tr>
        <td>
          <a href="{{ order.id }}" class="{% if order.order_status == '1' %}text-danger{% elif order.order_status == '2' or order.order_status == '3' %}text-warning{% elif order.order_status == '5' %}text-secondary{% else %}text-success{% endif %}">
            {{ order.get_order_status_display }}
          </a>
        </td>
        <td>{{ order.order_date }}</td>
        <td>{{ order.car.car_model }}</td>
          <td>{{ order.total_order_sum }} Eur</td>
      </tr>
    {% endfor %}
  </tbody>
</table>

<!--#puslapiavimas-->
<div style="text-align: center; font-size: 14px; color: #333;">
    <span class="step-links" style="display: inline-block;">
        {% if page_obj.has_previous %}
            <a href="?page=1" style="color: #333;">&laquo; pirmas</a>
            <a href="?page={{ page_obj.previous_page_number }}" style="color: #333;">atgal</a>
        {% endif %}

        <span class="current">
            {{ page_obj.number }} iš {{ page_obj.paginator.num_pages }}
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}" style="color: #333;">pirmyn</a>
            <a href="?page={{ page_obj.paginator.num_pages }}" style="color: #333;">paskutinis &raquo;</a>
        {% endif %}
    </span>
</div>

<section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">Album example</h1>
        <p class="lead text-body-secondary">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don’t simply skip over it entirely.</p>
        <p>
          <a href="#" class="btn btn-primary my-2">Main call to action</a>
          <a href="#" class="btn btn-secondary my-2">Secondary action</a>
        </p>
      </div>
    </div>
  </section>

  {% else %}
    <p>Customers' orders list is private</p>
  {% endif %}
{% endblock %}